### ISSUE TITLE
python vs_analysis.py 

### ISSUE THREAD

**Issue by sailseem** [Bioinformatics-Review/VS-Analysis#1]
Dear developer,
  May I ask one question, when I perform this analysis, i got the error like this 

File "vs_analysis.py", line 39, in <module>
    value = nextline[nextline.find("-+")+0:].split()[0]					#split at '-' and print binding affinity including '-'
IndexError: list index out of range

can you help me with it?
Thanks a lot

**Comment by MunibaFaiza** [comment]
Hi,

It is working fine on other systems.
Try the updated script and update your Python version.

Thank you.
